version: 2
updates:
- package-ecosystem: cargo
  directory: "/gwasm/compression"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/gwasm/prime-check"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/gwasm/md5-recursion"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
