language: rust

cache:
  cargo: true

env:
 - TASK=compression COMPILER=cargo-wasi RUST_BACKTRACE=1
 - TASK=compression COMPILER=wasm32-unknown-emscripten RUST_BACKTRACE=1
 - TASK=compression COMPILER=wasm32-wasi RUST_BACKTRACE=1
 - TASK=md5-recursion COMPILER=cargo-wasi RUST_BACKTRACE=1
 - TASK=md5-recursion COMPILER=wasm32-unknown-emscripten RUST_BACKTRACE=1
 - TASK=md5-recursion COMPILER=wasm32-wasi RUST_BACKTRACE=1
 - TASK=prime-check COMPILER=cargo-wasi RUST_BACKTRACE=1
 - TASK=prime-check COMPILER=wasm32-unknown-emscripten RUST_BACKTRACE=1
 - TASK=prime-check COMPILER=wasm32-wasi RUST_BACKTRACE=1

matrix:
  allow_failures:
    - env: TASK=compression COMPILER=cargo-wasi RUST_BACKTRACE=1
    - env: TASK=compression COMPILER=wasm32-unknown-emscripten RUST_BACKTRACE=1
    - env: TASK=compression COMPILER=wasm32-wasi RUST_BACKTRACE=1

os: linux
dist: bionic

rust:
 - nightly
 - beta
 - stable

install:
  
before_script:
  
before_cache:
  # this following line is recommended by travis docs if one overrides before_cache
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
  # for builds using rust nightly, we may aswell not attempt to cache target directory
  # as every night, this cache is no longer useful
  - rm -rfv $TRAVIS_BUILD_DIR/gwasm/$TASK/target/
  - cd $TRAVIS_BUILD_DIR/gwasm/$TASK/ && cargo clean -p $TASK
script:
  - cd $TRAVIS_BUILD_DIR/gwasm/$TASK/
  - cargo check
  - cargo check --no-default-features
  - cargo test
  - |
    cargo build
    if [ $COMPILER == "wasm32-wasi" ]
    then
      rustup target add wasm32-wasi
      cargo check --target wasm32-wasi
      cargo check --target wasm32-wasi --no-default-features
      cargo rustc --target=wasm32-wasi --release --verbose
    elif [ $COMPILER == "cargo-wasi" ]
    then
      cargo install cargo-wasi
      cargo wasi --version
      cargo wasi build
    elif [ $COMPILER == "wasm32-unknown-emscripten" ]
    then
      cd $TRAVIS_HOME
      git clone https://github.com/emscripten-core/emsdk.git
      cd emsdk
      ./emsdk install latest
      ./emsdk activate latest
      source ./emsdk_env.sh
      rustup target add wasm32-unknown-emscripten
      cd $TRAVIS_BUILD_DIR/gwasm/$TASK/
      cargo rustc --target=wasm32-unknown-emscripten --release --verbose -- -C link-args="-s BINARYEN_ASYNC_COMPILATION=0" --verbose
    fi

notifications:
  email:
    on_failure: always
    on_success: never
